spring:
  data:
    mongodb:
      database: book
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  shell:
    interactive:
#      enabled: false
      enabled: true
