spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  data:
    mongodb:
      uri: mongodb://root:prisma@localhost:27017
      database: book
      authentication-database: admin

logging:
  level:
    root: INFO

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2